runtime: python312
env: standard

instance_class: F2

entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8080

env_variables:
  API_KEY: "ftl-sustainable-ai-key"
  MODEL_REGISTRY_PATH: "models/latest/sustainability_classification_pipeline.pkl"
  CORS_ORIGINS: "*"
  LOG_LEVEL: "INFO"
  DEBUG: "false"
  ENVIRONMENT: "production"

handlers:
  - url: /.*
    script: auto